export const PATHWAYS: Record<string, string[]> = {
  "Methylation Cycle": ["MTHFR", "MTRR", "MTR", "CBS", "BHMT", "PEMT"],
  "Catecholamine Metabolism": ["COMT", "MAO-A", "MAO-B", "DBH"],
  "Caffeine Response": ["CYP1A2", "ADORA2A", "ADA"],
  "Blood Pressure": ["ACE", "AGT", "AGTR1", "GNB3", "ADRB1"],
  Inflammation: ["IL6", "TNF", "CRP", "IL10"],
  "Drug Metabolism - Phase I": [
    "CYP1A2",
    "CYP2C9",
    "CYP2C19",
    "CYP2D6",
    "CYP3A4",
    "CYP3A5",
  ],
  "Drug Metabolism - Phase II": ["NAT2", "GSTP1", "UGT1A1"],
  "Lipid Metabolism": ["APOE", "APOA2", "CETP", "PPARG", "PPARA"],
  "Vitamin Metabolism": ["GC", "BCMO1", "FUT2", "MTHFR"],
  "Circadian Rhythm": ["ARNTL", "PER2", "CLOCK"],
  "Muscle & Exercise": ["ACTN3", "PPARGC1A", "ADRB2", "ACE"],
};
